---
# NOTE!! THIS IS CURRENTLY EXPERIMENTAL AND UNDER DEVELOPMENT. SOME THINGS WILL CHANGE
job: extension
config:
  # this name will be the folder and filename name
  name: "sd3-5_medium_lora"
  process:
    - type: 'sd_trainer'
      # root folder to save training sessions/samples/weights
      training_folder: "new_output"
      # device: cuda:0
      device: cuda
#      trigger_word: "p3r5on"
      network:
        type: "lora"
        rank: 32
        conv: 32
        conv_alpha: 32
        linear: 32
        linear_alpha: 64 # Keeping alpha larger than rank increases the effect of LoRA
        network_kwargs:
          only_if_contains:
            - "ff."
            - "attn."
            - "transformer.pos_embed.proj"
      save:
        dtype: float16 # precision to save
        save_every: 1000 # save every this many steps
        max_step_saves_to_keep: 1 # how many intermittent saves to keep
        push_to_hub: false #change this to True to push your trained model to Hugging Face.
      datasets:
        - folder_path: "/pvc/MIMIC_ARRANGED/Train"
          caption_ext: "txt"
          caption_dropout_rate: 0.05  # will drop out the caption 5% of time
          shuffle_tokens: false  # shuffle caption order, split by commas
          cache_latents_to_disk: false  # leave this true unless you know what you're doing
          resolution: [ 1024 ] 
      train:
        batch_size: 64
        steps: 37092  # (len(dataset) * epochs) / batch_size  -> We have 237388 samples
        gradient_accumulation_steps: 1
        train_unet: true
        train_text_encoder: false  # May not fully work with SD3 yet
        gradient_checkpointing: true  # need the on unless you have a ton of vram
        noise_scheduler: "flowmatch"
        timestep_type: "linear" # linear or sigmoid
        optimizer: "adamw8bit"
        lr: 1e-4
        # uncomment this to skip the pre training sample
        skip_first_sample: true
        # uncomment to completely disable sampling
#        disable_sampling: true
        # uncomment to use new vell curved weighting. Experimental but may produce better results
#        linear_timesteps: true

        # ema will smooth out learning, but could slow it down. Recommended to leave on.
        ema_config:
          use_ema: true
          ema_decay: 0.99

        # will probably need this if gpu supports it for sd3, other dtypes may not work correctly
        dtype: bf16
      model:
        # huggingface model name or path
        name_or_path: "stabilityai/stable-diffusion-3.5-medium"
        is_v3: true
        quantize: true  # run 8bit mixed precision
      sample:
        sampler: "flowmatch" # must match train.noise_scheduler
        sample_every: 2000 # sample every this many steps
        width: 1024
        height: 1024
        prompts:
          # you can add [trigger] to the prompts here and it will be replaced with the trigger word
#          - "[trigger] holding a sign that says 'I LOVE PROMPTS!'"\
          - "Nasogastric tube extends to the mid body of the stomach, before coiling on itself so that the tip lies close to the esophagogastric junction. Cardiac silhouette is within normal limits and there is no vascular congestion, pleural effusion, or acute focal pneumonia."
          - 'PA and lateral views of the chest provided. Lung volumes are low with mild bibasilar atelectasis. No convincing signs of pneumonia or edema. No large effusion or pneumothorax is seen. The cardiomediastinal silhouette appears normal. There is no free air below the right hemidiaphragm. Fluid level is noted within the stomach.'
          - 'PA and lateral views of the chest provided. Lung volumes are low with mild bibasilar atelectasis. No convincing signs of pneumonia or edema. No large effusion or pneumothorax is seen. The cardiomediastinal silhouette appears normal. There is no free air below the right hemidiaphragm. Fluid level is noted within the stomach.'
          - 'Heart size top-normal. Lungs grossly clear. No pleural abnormality or evidence of central lymph node enlargement.'
          - 'The right costophrenic angle is not imaged. Otherwise, the lungs are clear. The heart size is upper limits of normal. Enteric tube courses below the level of the diaphragm. There is no pneumothorax.'
          - 'Single frontal view of the chest. NG tube is coiled in the stomach. Right PICC in lower SVC is unchanged in position. Cardiac size is normal. Mild bibasilar opacities consistent with atelectasis. There is no pneumothorax or pleural effusion.'
          - 'AP upright and lateral views of the chest provided. Mild basal atelectasis noted. Hilar congestion noted without frank edema. No large effusion or pneumothorax. Heart size is normal. Mediastinal contour is unchanged. Bony structures are intact. No free air below the right hemidiaphragm.'
          - 'No focal consolidation, pleural effusion, pneumothorax, or pulmonary edema is detected. Heart and mediastinal contours are within normal limits. Aortic arch calcifications are seen.'
          - 'Lung volumes are slightly low. This accentuates the size of the cardiac silhouette which is likely top normal. Mediastinal and hilar contours are unremarkable. Pulmonary vasculature is normal. No focal consolidation, pleural effusion or pneumothorax is present. There are mild degenerative changes in the thoracic spine.'
          - 'The lungs are clear without focal consolidation. No pleural effusion or pneumothorax is seen. The cardiac and mediastinal silhouettes are unremarkable.'
        neg: ""  
        seed: 42
        walk_seed: true
        guidance_scale: 4
        sample_steps: 25
# you can add any additional meta info here. [name] is replaced with config name at top
meta:
  name: "[name]"
  version: '1.0'
