---
# This configuration requires 20GB of VRAM or more to operate
job: extension
config:
  # this name will be the folder and filename name
  name: "lumina2_lora"
  process:
    - type: 'sd_trainer'
      # root folder to save training sessions/samples/weights
      training_folder: "output"
      # uncomment to see performance stats in the terminal every N steps
      performance_log_every: 500
      device: cuda
      # if a trigger word is specified, it will be added to captions of training data if it does not already exist
      # alternatively, in your captions you can add [trigger] and it will be replaced with the trigger word
      # trigger_word: "p3r5on"
      network:
        type: "lora"
        rank: 32
        linear: 32
        linear_alpha: 64 # Keeping alpha larger than rank increases the effect of LoRA
      save:
        dtype: bf16 # precision to save
        save_every: 1000 # save every this many steps
        max_step_saves_to_keep: 1 # how many intermittent saves to keep
        save_format: 'diffusers' # 'diffusers'
      datasets:
        - folder_path: "/pvc/MIMIC_ARRANGED/Train"
          caption_ext: "txt"
          caption_dropout_rate: 0.05  # will drop out the caption 5% of time
          shuffle_tokens: false  # shuffle caption order, split by commas
          # cache_latents_to_disk: true  # leave this true unless you know what you're doing
          resolution: [ 512, 768, 1024 ]  # lumina2 enjoys multiple resolutions
      train:
        batch_size: 32

        # can be 'sigmoid', 'linear', or 'lumina2_shift'
        timestep_type: 'lumina2_shift' 
        
        steps: 9000  # total number of steps to train 500 - 4000 is a good range
        gradient_accumulation: 1
        train_unet: true
        train_text_encoder: false  # probably won't work with lumina2
        gradient_checkpointing: true  # need the on unless you have a ton of vram
        noise_scheduler: "flowmatch" # for training only
        optimizer: "adamw8bit"
        lr: 1e-4
        # uncomment this to skip the pre training sample
        skip_first_sample: true
        # uncomment to completely disable sampling
        # disable_sampling: true

        # ema will smooth out learning, but could slow it down. Recommended to leave on if you have the vram
        ema_config:
          use_ema: true
          ema_decay: 0.99

        # will probably need this if gpu supports it for lumina2, other dtypes may not work correctly
        dtype: bf16
      model:
        # huggingface model name or path
        name_or_path: "Alpha-VLLM/Lumina-Image-2.0"
        is_lumina2: true # lumina2 architecture
        # you can quantize just the Gemma2 text encoder here to save vram
        quantize_te: true
      sample:
        sampler: "flowmatch" # must match train.noise_scheduler
        sample_every: 250 # sample every this many steps
        width: 1024
        height: 1024
        prompts:
          - "Nasogastric tube extends to the mid body of the stomach, before coiling on itself so that the tip lies close to the esophagogastric junction. Cardiac silhouette is within normal limits and there is no vascular congestion, pleural effusion, or acute focal pneumonia."
          - 'PA and lateral views of the chest provided. Lung volumes are low with mild bibasilar atelectasis. No convincing signs of pneumonia or edema. No large effusion or pneumothorax is seen. The cardiomediastinal silhouette appears normal. There is no free air below the right hemidiaphragm. Fluid level is noted within the stomach.'
          - 'PA and lateral views of the chest provided. Lung volumes are low with mild bibasilar atelectasis. No convincing signs of pneumonia or edema. No large effusion or pneumothorax is seen. The cardiomediastinal silhouette appears normal. There is no free air below the right hemidiaphragm. Fluid level is noted within the stomach.'
          - 'Heart size top-normal. Lungs grossly clear. No pleural abnormality or evidence of central lymph node enlargement.'
          - 'The right costophrenic angle is not imaged. Otherwise, the lungs are clear. The heart size is upper limits of normal. Enteric tube courses below the level of the diaphragm. There is no pneumothorax.'
          - 'Single frontal view of the chest. NG tube is coiled in the stomach. Right PICC in lower SVC is unchanged in position. Cardiac size is normal. Mild bibasilar opacities consistent with atelectasis. There is no pneumothorax or pleural effusion.'
          - 'AP upright and lateral views of the chest provided. Mild basal atelectasis noted. Hilar congestion noted without frank edema. No large effusion or pneumothorax. Heart size is normal. Mediastinal contour is unchanged. Bony structures are intact. No free air below the right hemidiaphragm.'
          - 'No focal consolidation, pleural effusion, pneumothorax, or pulmonary edema is detected. Heart and mediastinal contours are within normal limits. Aortic arch calcifications are seen.'
          - 'Lung volumes are slightly low. This accentuates the size of the cardiac silhouette which is likely top normal. Mediastinal and hilar contours are unremarkable. Pulmonary vasculature is normal. No focal consolidation, pleural effusion or pneumothorax is present. There are mild degenerative changes in the thoracic spine.'
          - 'The lungs are clear without focal consolidation. No pleural effusion or pneumothorax is seen. The cardiac and mediastinal silhouettes are unremarkable.'
        neg: ""
        seed: 42
        walk_seed: true
        guidance_scale: 4.0
        sample_steps: 25
# you can add any additional meta info here. [name] is replaced with config name at top
meta:
  name: "[name]"
  version: '1.0'
